config/routes.rb
Bankofdad::Application.routes.draw do

  devise_for :users

  authenticated do
    root 'customers#index', as: :authenticated_root
  end

  root 'guest#landing'
  
  resources :customers, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :transactions, only: [:index, :new, :create, :destroy]
    resource :allowance, only: [:edit, :update]
    resources :deposits, only: [:new, :create, :destroy]
  end

  get 'customers/:id/account/edit' => 'accounts#edit', as: :edit_customer_account
  patch 'customers/:id/account' => 'accounts#update', as: :account

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  belongs_to :user
  has_one :account, dependent: :destroy  
  has_one :allowance, dependent: :destroy
  has_many :deposits

  validates :name, presence: true, uniqueness: true

  before_validation(on: :create) do
    self.name = name.capitalize if name?
  end

  def to_param
    name
  end

  def net_worth
    account.balance
  end
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_filter :authenticate_user!
  before_action :set_customer, only: [:show, :edit, :update, :destroy, :settings]

  # GET /customers
  def index
    @customers = current_user.customers
  end

  # GET /customers/1
  def show
    @recent_transactions = Transaction.where(account: @customer.account).order('created_at DESC').limit(3)
    if @customer.account.interest > 0
      @next_interest_date = Date.today + (6 - Date.today.wday)  
    end
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @page_title = 'New customer'
  end

  # POST /customers
  def create
    customer = Customer.new(customer_params)
    customer.user = current_user
    customer.account = Account.default
    customer.allowance = Allowance.default
    if customer.save
      redirect_to customer, notice: 'Customer was successfully created.'    
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /customers/1
  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /customers/1
  def destroy
    @customer.destroy
    redirect_to customers_url
  end

  private
    def set_customer
      @customer = current_user.customers.find_by_name!(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_allowance.html.haml
.panel.panel-default
  .panel-body

    %h4
      Weekly allowance:
      - if @customer.allowance.amount == 0
        %strong.text-danger no
      - else
        %strong.text-success= "#{@customer.allowance.amount} #{@customer.account.currency}"
    - if @customer.allowance.amount != 0
      %span.glyphicon.glyphicon-calendar
      Next on
      = "#{Date::DAYNAMES[@customer.allowance.wday]},"
      = next_wday(@customer.allowance.wday)
    %p
    = link_to edit_customer_allowance_path(@customer), class: 'btn btn-primary btn-sm' do
      %span.glyphicon.glyphicon-cog
      = ' Setup allowance'

app/views/customers/_balance.html.haml
.panel.panel-default
  .panel-body

    %h3 Balance
    %h2{class: @customer.account.balance == 0 ? '' : 'text-success'}= "#{@customer.account.balance} #{@customer.account.currency}"
    = link_to new_customer_transaction_path(@customer, params: { operation: 'deposit' }), class: 'btn btn-success' do
      %span.glyphicon.glyphicon-plus
      = ' Deposit'
    = link_to new_customer_transaction_path(@customer, params: { operation: 'withdraw' }), class: 'btn btn-danger' do
      %span.glyphicon.glyphicon-minus
      = ' Withdraw'

app/views/customers/_form.html.haml
= form_for(@customer) do |f|
  - if @customer.errors.any?
    .alert.alert-danger
      %strong= pluralize(@customer.errors.count, "error")
      prohibited this customer from being saved:
      %ul
      - @customer.errors.full_messages.each do |msg|
        %li= msg
  
  .form-group
    = f.label :name 
    %br
    = f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Customer\'s name'
  = f.submit 'Confirm', class: 'btn btn-primary'
  = link_to customers_path, { class: 'btn btn-default' } do
    %span.glyphicon.glyphicon-cancel
    = ' Cancel'

app/views/customers/_instruments.html.haml
%table.table
  %thead
    %th Account
    %th Amount
    %th Interest
    %th Term
    %th Actions
  %tbody
    %tr
      %td 
        %span.glyphicon.glyphicon-play
        Checking account
      %td= "#{@customer.account.balance} #{@customer.account.currency}"
      %td
        = "#{@customer.account.interest}% monthly"        
      %td indefinite
      %td 
        = link_to edit_customer_account_path(@customer), class: 'btn btn-primary btn-xs' do
          %span.glyphicon.glyphicon-cog
          = 'Setup interest'
        

    - @customer.deposits.each do |deposit|
      %tr
        %td
          %span.glyphicon.glyphicon-time
          Term deposit 
          = deposit.duration_months == 12 ? '(1 year)' : "(#{pluralize(deposit.duration_months, 'month')})"
        %td= "#{deposit.amount} #{deposit.customer.account.currency}"
        %td= "#{deposit.interest}% at term"
        %td= deposit.term.to_s(:short_date)
        %td
          = link_to customer_deposit_path(@customer, deposit), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do
            %span.glyphicon.glyphicon-trash
            = ' Cancel'

= link_to new_customer_deposit_path(@customer), class: 'btn btn-primary btn-sm' do
  %span.glyphicon.glyphicon-time
  = ' Create term deposit'
%br

app/views/customers/_recent_transactions.html.haml
- if @recent_transactions.empty?
  No recent transactions.
- else
  %h4 Recent transactions
  %table.table.table-condensed
    %thead
      %tr
        %th Date
        %th Amount        
        %th Description
        %th
    %tbody
      - @recent_transactions.each do |transaction|
        %tr
          %td= transaction.created_at.to_s(:short_date)
          %td{ class: transaction.operation == 'deposit' ? 'text-success' : 'text-danger' }= "#{transaction.operation == 'deposit' ? '+' : '-'}#{transaction.amount}"
          %td= transaction.description
          %td
            - if transaction == @recent_transactions.first
              = link_to customer_transaction_path(@customer, transaction), method: :delete, class: 'text-danger', data: { confirm: 'Are you sure?' } do
                %span.glyphicon.glyphicon-trash
  = link_to customer_transactions_path(@customer), class: 'btn btn-info btn-sm' do
    %span.glyphicon.glyphicon-th-list
    = ' Transactions history'

app/views/customers/edit.html.haml
= render 'breadcrumbs', breadcrumbs: {'Customers' => customers_path, 'Edit customer' => nil}
.col-lg-4
  = render 'form', action: 'Update'

app/views/customers/index.html.haml
= render 'breadcrumbs', breadcrumbs: {'Your bank' => nil}
.page-header
  %h1 Your customers
- if @customers.empty?
  %p.well You have no customers.
- else
  %p.well= "You are managing the money of #{pluralize(@customers.size, 'customer')}"
  %table.table
    %thead
      %tr
        %th Name
        %th Net worth
        %th Actions
    %tbody
      - @customers.each do |customer|
        %tr
          %td
            = link_to customer.name, customer
          %td= "#{customer.account.balance} #{customer.account.currency}"
          %td
            = link_to customer, class: 'btn btn-info btn-xs' do
              %span.glyphicon.glyphicon-zoom-in
              = ' View'
            = link_to edit_customer_path(customer), class: 'btn btn-warning btn-xs' do
              %span.glyphicon.glyphicon-edit
              = ' Edit'
            = link_to customer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do
              %span.glyphicon.glyphicon-trash
              = ' Delete'
= link_to 'New customer', new_customer_path, class: 'btn btn-primary'

app/views/customers/new.html.haml
= render 'breadcrumbs', breadcrumbs: {'Customers' => customers_path, 'Create new customer' => nil}
.col-md-6
  = render 'form', action: 'Create'

app/views/customers/show.html.haml
= render 'breadcrumbs', breadcrumbs: {'Customers' => customers_path, @customer.name => nil}

/
  .row
    .col-lg-12
      .page-header
        %h1= "#{@customer.name}'s account"

.row
  .col-lg-3
    = render 'balance'
    = render 'allowance'
  .col-lg-9
    = render 'instruments'

%hr
.row
  .col-lg-12
    = render 'recent_transactions'


%p

/
  .row
    .col-lg-12
      = link_to 'Back to customers', customers_path, class: 'btn btn-default'