config/routes.rb
Bankofdad::Application.routes.draw do

  devise_for :users

  authenticated do
    root 'customers#index', as: :authenticated_root
  end

  root 'guest#landing'
  
  resources :customers, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :transactions, only: [:index, :new, :create, :destroy]
    resource :allowance, only: [:edit, :update]
    resources :deposits, only: [:new, :create, :destroy]
  end

  get 'customers/:id/account/edit' => 'accounts#edit', as: :edit_customer_account
  patch 'customers/:id/account' => 'accounts#update', as: :account

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/allowance.rb
class Allowance < ActiveRecord::Base

  belongs_to :customer

  validates :amount, numericality: true
  validates :wday, numericality: { 
    greater_than_or_equal_to: 0, 
    less_than_or_equal_to: 6, 
    message: 'is not a valid day of the week'
  }

  def self.default
    Allowance.new do |a|
      a.amount = 0
      a.wday = 0
    end
  end

end

app/controllers/allowances_controller.rb
class AllowancesController < ApplicationController
  
  before_filter :authenticate_user!
  before_action :set_customer, only: [:edit, :update]
  
  # GET /allowances/1/edit
  def edit
    @allowance = @customer.allowance
    @page_title = 'Modify allowance'
  end

  # PATCH/PUT /allowances/1
  def update
    if @customer.allowance.update(allowance_params)
      redirect_to @customer, notice: 'Allowance was successfully updated.'
    else
      render action: 'edit'
    end
  end

  private
    def set_customer
      @customer = current_user.customers.find_by_name!(params[:customer_id])
    end

    def allowance_params
      params.require(:allowance).permit(:wday, :amount)
    end
end

app/helpers/allowances_helper.rb
module AllowancesHelper
end

app/views/allowances/_form.html.haml
= form_for(@allowance, url: customer_allowance_url) do |f|
  - if @allowance.errors.any?
    .alert.alert-danger
      %h2= "#{pluralize(@allowance.errors.count, "error")} prohibited this allowance from being saved:"
      %ul
      - @allowance.errors.full_messages.each do |msg|
        %li= msg

  .form-group
    = f.label 'Every week on'
    = f.select :wday, Date::DAYNAMES.map { |d| [d, Date::DAYNAMES.index(d)]}, {}, { class: 'form-control' }
  .form-group
    = f.label :amount
    .input-group
      = f.text_field :amount, class: 'form-control'
      %span.input-group-addon= @customer.account.currency
  %div
    = f.submit 'Confirm', class: 'btn btn-primary'
    = link_to 'Back', @customer, class: 'btn btn-default'

app/views/allowances/edit.html.haml
= render 'breadcrumbs', breadcrumbs: {'Customers' => customers_path, @customer.name => @customer, 'Setup allowance' => nil}
.col-lg-4
  = render 'form'

app/views/allowances/new.html.haml
= render 'breadcrumbs', breadcrumbs: {'Customers' => customers_path, @customer.name => @customer, 'Setup allowance' => nil}
.col-lg-4
  = render 'form'