config/routes.rb
Bankofdad::Application.routes.draw do

  devise_for :users

  authenticated do
    root 'customers#index', as: :authenticated_root
  end

  root 'guest#landing'
  
  resources :customers, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :transactions, only: [:index, :new, :create, :destroy]
    resource :allowance, only: [:edit, :update]
    resources :deposits, only: [:new, :create, :destroy]
  end

  get 'customers/:id/account/edit' => 'accounts#edit', as: :edit_customer_account
  patch 'customers/:id/account' => 'accounts#update', as: :account

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= @page_title || 'Bank of Dad'
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    = csrf_meta_tags

    %link{rel: 'stylesheet', href: '//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css', media: 'screen'}
    %link{rel: 'stylesheet', href: '//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css', media: 'screen'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'true'

    = yield(:header)

  %body
    #wrap
      .navbar.navbar-default.navbar-static-top
        .container
          .navbar-header
            %button.navbar-toggle{type: 'button', 'data-toggle' => 'collapse', 'data-target' => '.navbar-collapse'}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{href: '/'}
              %strong bankofdad.eu
          .navbar-collapse.collapse
            %ul.nav.navbar-nav
              %li.active
                = link_to 'Home', customers_path
              %li
                %a{href: '#'} About
            - if user_signed_in?
              %ul.nav.navbar-nav.navbar-right
                %li.active
                  %a
                    %strong= current_user.email
                %li.active
                  = link_to edit_user_registration_path do
                    %span.glyphicon.glyphicon-cog
                %li
                  = link_to destroy_user_session_path, method: :delete do
                    %span.glyphicon.glyphicon-log-out
                    = ' Sign out'
            - else
              = form_for(resource, :as => resource_name, :url => session_path(resource_name), html: {class: 'navbar-form navbar-right'}) do |f|
                .form-group
                  = f.email_field :email, class: 'form-control', placeholder: 'Email address'
                .form-group
                  = f.password_field :password, class: 'form-control', placeholder: 'Password'
                = f.hidden_field :remember_me, value: true
                = f.submit 'Sign in', class: 'btn btn-primary'
                = link_to 'Register', new_user_registration_path, class: 'btn btn-success'

      .container
        - if notice
          .alert.alert-success.alert-dismissable
            %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'}
              &times;
            = notice
        - if alert
          .alert.alert-warning.alert-dismissable
            %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'}
              &times;
            = alert
        = yield

    %script{src: '//code.jquery.com/jquery.js'}
    %script{src: '//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js'}
    %script{src: '//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js'}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    

    :javascript
      $(document).ready(function() {
        var timeZone = jstz.determine();
        document.cookie = 'jstz_time_zone=' + timeZone.name();
      });
    
    